// The single editable source of truth for the quiz. correctAnswer uses zero-based indexes.
// visualLocation selects the surrounding scene without changing quiz logic.
const quizCityDetails = {
  Paris: { chapter: 'La Ville Lumière', subtitle: 'Lanterns glow above the rooftops.', accent: 'paris', order: 0 },
  Nice: { chapter: 'La Côte d’Azur', subtitle: 'The Riviera waits beyond the blue hour.', accent: 'nice', order: 1 },
  Lyon: { chapter: 'La Capitale des Gaules', subtitle: 'Lantern-lit streets hide the next clue.', accent: 'lyon', order: 2 },
  Bordeaux: { chapter: 'La Belle Endormie', subtitle: 'A final secret rests by the river.', accent: 'bordeaux', order: 3 }
};

const quizQuestions = [
  { id: 1, city: 'Paris', cityChapter: 'La Ville Lumière', question: 'You enter a Parisian café. The waiter smiles and says: “Bonjour ! Comment allez-vous ?” Which reply fits best?', options: ["Je m'appelle Paris.", 'Je vais bien, merci.', "J'ai quinze ans.", 'Je suis étudiant.'], correctAnswer: 1, explanation: 'Je vais bien, merci. is an appropriate response to Comment allez-vous ?', visualLocation: 'paris-cafe' },
  { id: 2, city: 'Paris', cityChapter: 'La Ville Lumière', question: 'A French postcard has this written on it: “J’habite ___ Paris.” Which little word completes the sentence?', options: ['à', 'au', 'aux', 'en'], correctAnswer: 0, explanation: 'The preposition à is used with a city: J’habite à Paris.', visualLocation: 'paris-postcard' },
  { id: 3, city: 'Paris', cityChapter: 'La Ville Lumière', question: 'Inside a château room, you find a family portrait. The note says: “Voici la sœur de Marc.” Who is she?', options: ["Marc's mother", "Marc's brother", "Marc's sister", "Marc's daughter"], correctAnswer: 2, explanation: 'La sœur means sister.', visualLocation: 'paris-family-portrait' },
  { id: 4, city: 'Paris', cityChapter: 'La Ville Lumière', question: 'A French treasure chest has a combination: “Dix — quinze — vingt — ?” Which number comes next?', options: ['vingt-deux', 'vingt-cinq', 'trente', 'trente-cinq'], correctAnswer: 1, explanation: 'The sequence rises by five: dix, quinze, vingt, vingt-cinq.', visualLocation: 'paris-treasure-chest' },
  { id: 5, city: 'Paris', cityChapter: 'La Ville Lumière', question: 'A note says: “La Tour Eiffel est ___ dans cette illustration.” The tower is painted black. Which answer agrees with the feminine noun?', options: ['noir', 'noire', 'noirs', 'noires'], correctAnswer: 1, explanation: 'Tour is feminine, so noir becomes noire.', visualLocation: 'paris-eiffel-tower' },
  { id: 6, city: 'Nice', cityChapter: 'La Côte d’Azur', question: 'You meet someone on the Promenade des Anglais. They say: “Salut ! Je m’appelle Camille. Et toi ?” What is the most natural response?', options: ["Je m'appelle Riya.", "J'ai Riya.", "Je suis m'appelle Riya.", 'Mon suis Riya.'], correctAnswer: 0, explanation: 'Je m’appelle... is the natural way to introduce yourself.', visualLocation: 'nice-promenade' },
  { id: 7, city: 'Nice', cityChapter: 'La Côte d’Azur', question: 'A clock in Nice shows 8:00 AM. A guide asks: “Quelle heure est-il ?” Which answer is correct?', options: ['Il est huit heures.', 'Elle est huit heures.', "C'est huit heure.", 'Il a huit heures.'], correctAnswer: 0, explanation: 'French tells the time with Il est...', visualLocation: 'nice-clock-tower' },
  { id: 8, city: 'Nice', cityChapter: 'La Côte d’Azur', question: 'Your next challenge is Wednesday. The calendar gives you: lundi → mardi → mercredi → ? Which day comes next?', options: ['vendredi', 'jeudi', 'dimanche', 'samedi'], correctAnswer: 1, explanation: 'Jeudi follows mercredi.', visualLocation: 'nice-calendar' },
  { id: 9, city: 'Nice', cityChapter: 'La Côte d’Azur', question: 'A sign outside a museum reads: “Nous ___ étudiants.” Which word unlocks the door?', options: ['avons', 'êtes', 'sommes', 'sont'], correctAnswer: 2, explanation: 'Nous sommes is the nous form of être.', visualLocation: 'nice-museum-door' },
  { id: 10, city: 'Nice', cityChapter: 'La Côte d’Azur', question: 'A character says: “J’ai 19 ans.” What does this mean?', options: ['I am 19 years old.', 'I have 19 brothers.', 'I live at number 19.', 'I was born in 19.'], correctAnswer: 0, explanation: 'French expresses age with avoir: J’ai 19 ans.', visualLocation: 'nice-birthday-chest' },
  { id: 11, city: 'Lyon', cityChapter: 'La Capitale des Gaules', question: 'You enter a room containing a table and a chair. The sign reads: “___ table et ___ chaise.” Which pair is correct?', options: ['le, le', 'la, le', 'la, la', 'un, un'], correctAnswer: 2, explanation: 'Table and chaise are feminine nouns: la table, la chaise.', visualLocation: 'lyon-interior' },
  { id: 12, city: 'Lyon', cityChapter: 'La Capitale des Gaules', question: 'You want one coffee in a French café. Which sentence is appropriate?', options: ['Je voudrais un café.', 'Je voudrais une café.', 'Je veux des café.', 'Je suis un café.'], correctAnswer: 0, explanation: 'Un café is masculine, and Je voudrais is a polite request.', visualLocation: 'lyon-cafe' },
  { id: 13, city: 'Lyon', cityChapter: 'La Capitale des Gaules', question: 'You find a portrait with the clue: “Marie est petite et Paul est grand.” Which statement is correct?', options: ['Marie is tall and Paul is short.', 'Both are tall.', 'Marie is short and Paul is tall.', 'Both are short.'], correctAnswer: 2, explanation: 'Petite means short and grande means tall.', visualLocation: 'lyon-portrait-gallery' },
  { id: 14, city: 'Lyon', cityChapter: 'La Capitale des Gaules', question: 'A notebook label says: “C’est ___ livre.” The book belongs to Jean. Which sentence means “It is Jean’s book”?', options: ['C’est son livre.', 'C’est sa livre.', 'C’est ses livre.', 'C’est leur livre.'], correctAnswer: 0, explanation: 'Son agrees with the masculine noun livre.', visualLocation: 'lyon-library' },
  { id: 15, city: 'Lyon', cityChapter: 'La Capitale des Gaules', question: 'A student introduces their family: “J’ai un frère et deux sœurs.” How many siblings are mentioned?', options: ['2', '3', '4', '5'], correctAnswer: 1, explanation: 'One brother plus two sisters makes three siblings.', visualLocation: 'lyon-family-room' },
  { id: 16, city: 'Bordeaux', cityChapter: 'La Belle Endormie', question: 'You find this sentence: “Nous sommes à Bordeaux et nous avons une voiture.” Which statement is correct?', options: ['They are in Bordeaux and they have a car.', 'They live in Paris and have a bicycle.', 'They are in Bordeaux and have a house.', 'They are travelling to Bordeaux without a car.'], correctAnswer: 0, explanation: 'The sentence says they are in Bordeaux and have a car.', visualLocation: 'bordeaux-diary' },
  { id: 17, city: 'Bordeaux', cityChapter: 'La Belle Endormie', question: 'A waiter says: “Je voudrais deux croissants et une baguette.” What does the waiter want?', options: ['One croissant and two baguettes.', 'Two croissants and one baguette.', 'Two baguettes and one croissant.', 'Three croissants.'], correctAnswer: 1, explanation: 'Deux is two; une is one.', visualLocation: 'bordeaux-bakery' },
  { id: 18, city: 'Bordeaux', cityChapter: 'La Belle Endormie', question: 'The gate shows: “Marie et Sophie ___ françaises.” Which key opens the gate?', options: ['est', 'suis', 'sont', 'êtes'], correctAnswer: 2, explanation: 'Sont is the ils/elles form of être.', visualLocation: 'bordeaux-castle-gate' },
  { id: 19, city: 'Bordeaux', cityChapter: 'La Belle Endormie', question: 'You are preparing a French cultural presentation. Which city is most famously associated with the Eiffel Tower?', options: ['Lyon', 'Nice', 'Bordeaux', 'Paris'], correctAnswer: 3, explanation: 'The Eiffel Tower is Paris’s iconic landmark.', visualLocation: 'bordeaux-culture-room' },
  { id: 20, city: 'Bordeaux', cityChapter: 'La Belle Endormie', question: 'The final parchment says: “Je parle français, j’aime la musique et j’habite à Lyon.” Which statement is NOT mentioned?', options: ['The person speaks French.', 'The person likes music.', 'The person lives in Lyon.', 'The person is a student.'], correctAnswer: 3, explanation: 'The sentence says nothing about being a student.', visualLocation: 'bordeaux-final-seal' }
];

// Expose the data for direct file opening, where browser module imports may be blocked.
window.FrenchCastleManiaData = { cityDetails: quizCityDetails, questions: quizQuestions };
